### ISSUE TITLE
Allow serializing the iterators

### ISSUE THREAD

**Issue by kewisch** [dankogai/js-combinatorics#13]
I'd like to save the state of the iterator to a file, so that I can continue iterating at that exact point on next run. A few values are held via closure, so I can't just serialize the iterator itself. Any ideas?

**Comment by dankogai** [comment]
You can save the seed array and its index then use .nth(index) to resume.

**Comment by kewisch** [comment]
Thanks, setting `cp.index` to the previous value seems to do it for the cartesian product!
