### ISSUE TITLE
Make available as bower package

### ISSUE THREAD

**Issue by atavakoli** [dankogai/js-combinatorics#15]
I'm requesting that this project be registered as [bower.io](http://bower.io/docs/creating-packages/) package. As it is already a node package & meets the naming & versioning requirements, I don't believe there are any major difficulties in getting this done.

I would be happy to submit a PR with `bower.json` if you agree.

Thanks for your consideration!

**Comment by thefabulousdev** [comment]
+1

**Comment by dankogai** [comment]
No objection.  Just give me `bower.json` or send me a pull request.

**Comment by sophietk** [comment]
Hi, I registered your module on bower.io. No `bower.json` is needed: available versions and other meta data are parsed from Github.
Now it's possible to require it:
```bash
bower i js-combinatorics
```
