### ISSUE TITLE
Make available as meteor package

### ISSUE THREAD

**Issue by JoeyAndres** [dankogai/js-combinatorics#18]
I'll fork and create a pull request.

**Comment by JoeyAndres** [comment]
I've created the package in my local machine, but I just realize I'll have to use jandres:js-combinatorics where jandres in the user. 

Is it fine if its like that? The preferred way is **dangkogai:js-combinatorics**, but that needs you need atmosphere account.

Tell me and I'll push my local commit and file a pull-request.

**Comment by dankogai** [comment]
Please PR me.  PR is always welcome so long as it does not break other package environments.

**Comment by JoeyAndres** [comment]
Pull requested is now filed.
