### ISSUE TITLE
A question of curiosity: why the strange syntax to retrieve combinations?

### ISSUE THREAD

**Issue by ilyador** [dankogai/js-combinatorics#20]
I don't understand `while(a = cmb.next()) console.log(a)`
`a` seems to be an array, so why is it an array of the single options? And what is this `next()`?

**Comment by blanchg** [comment]
cmb in this case is a generator function.  Depending on your usage this can make the library very fast and very memory efficient as it only generates the next value on request.  

There is nothing stopping you from manually aggregating all the .next() results into an array.

```javascript
var results = [];
while (a = cmb.next())
    results[results.length] = a;
```
