### ISSUE TITLE
Using the Cartesian product with the big Combination without using the toArray them?

### ISSUE THREAD

**Issue by leonardovff** [dankogai/js-combinatorics#22]
Because I have a lot of combinations, ranging from billion. I'm not using the toArray bigCombinations, memory usage goes it up high.

**Comment by blanchg** [comment]
The implementation creates a plain JavaScript array to take care of the progression. This means an array that is x elements of JavaScript numbers.  It only stores 0 and 1 so it might be possible to optimize this using a bit array or even a uint8array but I am traveling right now and can't look at it.

**Comment by blanchg** [comment]
I had a look at changing the implementation today, it doesn't fix the memory usage.  Creating an array of a billion numbers is as good as it gets without implementing it in multi integer bitwise operations.  And I don't have time to do that.
