### ISSUE TITLE
NPM-published 0.5.0 code does not reflect 0.5.0 API

### ISSUE THREAD

**Issue by namuol** [dankogai/js-combinatorics#25]
The `bigCombination` function is not available in the version that exists on NPM, which suggests that the actual published code is out of sync with the published API.

See here: https://tonicdev.com/5709d318ded58c1100e6eb36/5709d318ded58c1100e6eb37

**Comment by dankogai** [comment]
I just bumped version to 0.5.1 then `npm publish`'ed.  This should fix the issue.

**Comment by namuol** [comment]
Thanks for the quick fix! :beers:
