### ISSUE TITLE
`permutation` with larger arrays (> 32 entries) issue

### ISSUE THREAD

**Issue by dandar3** [dankogai/js-combinatorics#34]
`permutation()` behaves strangely with input arrays with more than 32 entries.

Somehow it seems to only consider the first number of entries as difference from a multiple of 32 - e.g. from an input of 71 entries it only used the first 7 [ _71 - 2 \* 32 = 7_ ].

Poking around `permutation()` function and noticing the `bigCombination()` variant, I found that using that instead of `combination()` makes it work correctly. 

I don't know whether you want to introduce a new `bigPermutation()` function or maybe just patch existing `permutation()` function:

```
var permutation = function(ary, nelem, fun) {
        [...]
        addProperties(that, {
            valueOf: function() {
                return size;
            },
            init: function() {
                this.cmb = (ary.length <= 32 ? combination(ary, nelem) : bigCombination(ary, nelem));
                this.per = _permutation(this.cmb.next());
            },
        [...]
}
```

**Comment by battila7** [comment]
I have just ran into the same issue and used the same solution as @dandar3 described.

It'd be great if this issue was fixed.
