### ISSUE TITLE
Licence file 

### ISSUE THREAD

**Issue by meeple142** [dankogai/js-combinatorics#35]
Thank you for a great library. 
I see in the package.json file you say the licence is BSD but you don't have a licence file in the repository. 

Thanks!

**Comment by Steviey** [comment]
+1

**Comment by dankogai** [comment]
Upon your request https://github.com/dankogai/js-combinatorics/commit/036a57ce1e4ff75aaafbefbaf7020b310f25c4dc

**Comment by meeple142** [comment]
Great! But is it dual licensed BSD and MIT? The [package.json](https://github.com/dankogai/js-combinatorics/blob/master/package.json#L28) file says BSD?

**Comment by dankogai** [comment]
Fixed package.json so it is MIT license https://github.com/dankogai/js-combinatorics/commit/31069badb1c916a10e96f5f75b091d32a769ea05

MIT is my license of choice and I usually start the project with it so I have been thinking this has been under MIT...
