### ISSUE TITLE
baseN size limiter

### ISSUE THREAD

**Issue by carloshximenes** [dankogai/js-combinatorics#60]
I'm using baseN to create a 11x11 array.
```
const values = [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2];
const allCombinations = Combinatorics.baseN(values, 11).toArray();
```
I'm with the out-of-memory error. So i'm wondering if is there a way to limit my result string to show my only the firsts X results?

Thanks.

**Comment by blanchg** [comment]
Instead of calling toArray use the iterator to get just the results you
need. You can get them one at a time then with minimal memory usage.

**Comment by carloshximenes** [comment]
Sorry, I'm new on JS so can you help me with an example? Thanks.

**Comment by blanchg** [comment]
Look at the Generator Methods in the documentation
https://github.com/dankogai/js-combinatorics#generator-methods

let cmb = Combinatorics.combination(['a','b','c','d'], 2);
let i = 0;
while(a = cmb.next() && i < 10) {
    console.log(a);
    i++;
}

**Comment by carloshximenes** [comment]
Thanks!

```
const values = [1,2,3,4,5,6,7,8,9];
const allCombinations = jsCombinatorics.baseN(values, 11);

const results = [];
for (let i = 0; i < 5; i++) {
  results.push(allCombinations.next());
}

console.log(results);
```
