### ISSUE TITLE
baseN start from last

### ISSUE THREAD

**Issue by xcool456** [dankogai/js-combinatorics#61]
Hi. I'm using baseN to create a combinations from 10 elements(numbers and letters).
I save each array to a file.
Can i somehow start with the last array if I stop generating combinations?

**Comment by carloshximenes** [comment]
Hi, i'm getting out of memory error when i'm trying to create a 11x11 array.
Can you share your code to help me fix this error?
Thanks.

**Comment by dankogai** [comment]
Now that `js-combinatorics` is completely (and incompatibly :-) rewritten, I will close this issue for the time being. if you still have the same problem w/ newer version, please open a new issue.
