### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by mwgamble** [dankogai/js-combinatorics#66]
It would be great if this package could gain native typescript support. With the 1.0.0 upgrade, this package has become unusable for me because the type definitions provided by DefinitelyTyped are now out of date. It's easier for me to just switch to another package that's natively written in Typescript, where the type definitions will always be in sync.

**Comment by dankogai** [comment]
You've got it!  From version 1.2.0 and on, it is now written in TypeScript!

https://github.com/dankogai/js-combinatorics/commit/0e7f2ec999e87111f945fd55bdd5f21300672b5b

**Comment by Michsior14** [comment]
@dankogai Could you not publish ts sources to the npm repository? It causes local recompilation of distributed files and errors if project uses different, more strict tsconfig parameters.

**Comment by dankogai** [comment]
Okay.  I've learned a lesson.  Just `.js` and `.d.ts` for npm.  `.ts` on git repo.

**Comment by mwgamble** [comment]
I think you can resolve this issue more neatly by putting the typescript source files into a `src` directory, and the compiled javascript file into a `dist` directory. By setting the `main` option in `package.json` to `dist/myfile.js`, there won't be a typescript source file alongside the compiled javascript file, and so typescript shouldn't find it.

It's definitely possible to do this, because many big-name projects (like Vuetify) manage it just fine. IMO it's always important to distribute the the unminified source with your packages, so that people can more easily read the code if need be.
