### ISSUE TITLE
Wrong combinations

### ISSUE THREAD

**Issue by timichal** [dankogai/js-combinatorics#70]
The combination algorithm seems to be buggy since 1.x. 

As of 1.3.0 `[...new Combination([1, 2, 3, 4, 5], 2)]` returns the following array: 
`[[1,2],[1,3],[1,4],[2,1],[2,3],[3,1],[2,4],[3,2],[3,5],[5,1]]`

whereas e.g. Python's itertools library returns the correct 
`[[1,2],[1,3],[1,4],[1,5],[2,3],[2,4],[2,5],[3,4],[3,5],[4,5]]`.

**Comment by dankogai** [comment]
Wow, this is a serious bug!

Fixed in 8fe18083e7ce0bebe93f2c728276ede13c4740ef .
