### ISSUE TITLE
SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by bennycode** [dankogai/js-combinatorics#77]
I am getting the following error when using "js-combinatorics" v1.4.5 with "ts-node" in my TypeScript code:

> $ cross-env NODE_ENV=test NODE_DEBUG=error nyc --nycrc-path=nyc.config.json jasmine --config=jasmine.json
> C:\dev\projects\bennycode\lambot-1\node_modules\js-combinatorics\combinatorics.js:14
> export const version = '1.4.5';
> ^^^^^^
> SyntaxError: Unexpected token 'export'

```ts
import {BaseN} from 'js-combinatorics';
const iterator = new BaseN(seedValues, length);
```

I don't have this error when using "js-combinatorics" v0.6.1 in conjunction with "@types/js-combinatorics" v0.5.32:

```ts
import Combinatorics from 'js-combinatorics';
const iterator = Combinatorics.baseN(seedValues, length);
```

**Comment by shirshak55** [comment]
@bennycode yea i was facing same issue so i forked it. Try it if you like https://github.com/shirshak55/js-combinatorics

in package.json
"ts-combinatorics": "1.0.0"

There is no reason to trust me for that you can fork it :)

**Comment by dankogai** [comment]
Try preloading [esm].  `npm install esm` then add `NODE_OPTIONS='-r esm'` before `nyc`

[esm]: https://github.com/standard-things/esm

See also: https://github.com/dankogai/js-combinatorics#commonjs-nodejs

**Comment by shirshak55** [comment]
@dankogai i did saw that and tried but it gave same error. So didn't fight with that one.

I  am not using repl just plain ts and node js.

**Comment by dankogai** [comment]
I am not familiar with your `nyc` command but AFAIK your javascript runtime does not support ES module.  Instead of `import` what happens if you did the following (assuming you have `esm` installed)?

```javascript
require=require("esm")(module);
var Combinatorics=require("js-combinatorics");
const iterator = Combinatorics.baseN(seedValues, length);
```

**Comment by shirshak55** [comment]
same error. What is nyc? I am just using v14.14.0 which should support es module. 

Typescript is using commonjs which may be creating issue but if I don't use common js other package starts to give error.

**Comment by dankogai** [comment]
Sorry `nyc` is from the example of @bennycode.  node14 does not support ES module `import` *statement* (though `import()` function is supported).  You still need `esm` or `babel`.

**Comment by shirshak55** [comment]
@dankogai hmm i am using typescript so i thought babel or esm would be optional. No idea why its not working .

**Comment by dankogai** [comment]
nodejs is only capable of running js.  tsc compiles .ts to .js.  `combinatorics.ts` is compiled to `combinatorics.js` with ` --target es6`.  So `combinatorics.js` is not nodejs compatible without es6 enablers like `esm` or `babel`.

**Comment by bennycode** [comment]
@dankogai thank you for taking the time and your detailed explanation. It helped a lot! 

I am running my tests with `jasmine` which is started via `nyc` and `nyc` registers the TypeScript compiler, so a lot of tools come into play. Thanks to you I found a combination that works for me. Here is my "start" script from my `package.json` file:

```
"test": "cross-env NODE_OPTIONS=\"-r esm\" nyc --nycrc-path=nyc.config.json jasmine --config=jasmine.json"
```

And this is my `nyc.config.json`:

```json
{
  "all": false,
  "check-coverage": false,
  "exclude": ["**/*.d.ts", "**/*.test*.ts", "**/index.ts", "**/demo/**/*"],
  "extension": [".ts"],
  "include": ["src/**/*.ts"],
  "per-file": false,
  "reporter": ["text-summary"],
  "require": ["ts-node/register"]
}
```

And my `jasmine.json`:

```
{
  "helpers": ["test/helpers/initTestDatabase.ts"],
  "random": true,
  "spec_dir": "src",
  "spec_files": ["**/*.test.ts"],
  "stopSpecOnExpectationFailure": true
}
```

As you suggested, I had to install the `esm` package (v3.2.25)  to make it work.

**Comment by shirshak55** [comment]
sorry for being late i tried commonjs/combinatorics.js and it worked so I am fine here :)
