### ISSUE TITLE
Question: Unexpected token 'export' using Babel

### ISSUE THREAD

**Issue by senda-dev** [dankogai/js-combinatorics#78]
Hi, I'm using Babel and I've the current `.babelrc` configuration:

```
{
  "presets": ["@babel/preset-env"],
  "plugins": ["@babel/plugin-transform-runtime"]
}
```

This let me use new ES syntax (export/import). But when I run Babel, I get the unexpected token error using `js-combinatorics@1.4.5`.

I need extra configuration for this library?

Thank you very much.

**Comment by pedrofracassi** [comment]
Hey, I'm getting the same problem when trying to use this lib (TypeScript being transpiled with ts-watch). I've tried many targets on `tsconfig.json`, but without any luck.

**Comment by dankogai** [comment]
You may need to install `@babel/register`.  Run

```sh
npm install @babel/core @babel/preset-env @babel/plugin-transform-runtime @babel/register
```

And try agin.

**Comment by pedrofracassi** [comment]
I ended up using the `ts-combinatorics` fork, which fixed the issue for me.

**Comment by stoplion** [comment]
Same error with NextJS
