### ISSUE TITLE
Rollup: Missing Export: 'BaseN' is not exported by "file"

### ISSUE THREAD

**Issue by OsgoodSchlatter** [dankogai/js-combinatorics#88]
I'm building a stellar wallet following the stellar documentation. I'm currently at the "make XLM payments" section, and finished it. 
When i run 'npm start', it gives me this message : 
[ ERROR ]  Rollup: Missing Export: src/components/loader/lazy_evjuzzidv4juchsqhiofgq-loader.js:2:9
           'BaseN' is not exported by node_modules/js-combinatorics/combinatorics.js

      L1:  import { registerInstance as __stencil_registerInstance } from "@stencil/core";
      L2:  import { BaseN } from "js-combinatorics";
      L3:  import { h } from "@stencil/core";

I've no idea why baseN isnt exported, and I've tried exporting it manually from the node_modules file, but nothing worked. I've downloaded again the js-combinatorics node_module but it didnt change anything.
has anyone faced the same issue ? 

thanks in advance

**Comment by dankogai** [comment]
It should've been closed when the pr was merged.
